name: Test Firebat Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      - self-hosted
      - linux
      - x64
      - production
      - deploy

    steps:
      - name: Check runner
        shell: bash
        run: |
          set -euo pipefail

          echo "===== USER ====="
          whoami
          id

          echo
          echo "===== HOST ====="
          hostname

          echo
          echo "===== DOCKER ====="
          docker --version
          docker compose version

          echo
          echo "===== DEPLOY SCRIPT ====="
          sudo -l